Repository Team-E2I4/Team-E2I4-TiKiTaza-FE, pull requests merged in 2024-03, with the labels that each got.

#100 [Docs] 버그리포트 이슈템플릿 추가
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#114 [Feat] 인게임 타이머 기능 구현
  src/common/Timer/Timer.tsx
Labels: feat

#122 [Feat]: StartPage에 진입시 토큰있으면 삭제하는 로직 추가
  src/pages/StartPage/StartPage.tsx
Labels: feat, fix

#139 [Feat]: 타이머 로직 추가, 훅으로 분리
  src/common/Timer/constants/time.ts
  src/common/Timer/utils/convertTime.ts
  src/hooks/useTimer.ts
Labels: feat, refactor

#141 [Feat] 선택된 게임모드 store에서 연결
  src/pages/GamePage/GameCode/GameCode.tsx
  src/pages/GamePage/GamePage.tsx
Labels: feat

#166 [Fix] Vercel SPA 새로고침 에러 수정
  vercel.json
Labels: fix

#167 [Feat] 현재 접속자 기능 추가
  src/apis/api.ts
  src/hooks/useOnlineUsers.tsx
  src/pages/MainPage/MainPage.tsx
  src/pages/MainPage/UserList.tsx
Labels: feat

#175 [Fix] sse Timeout 서버에 맞게 60초로 변경
  src/pages/MainPage/SSEErrorBoundary.tsx
Labels: fix

#183 [Fix] 실시간 접속자수 실시간 폴링
  src/hooks/useOnlineUsers.tsx
Labels: fix

#195 [Feat] Timer 수정
  src/common/Timer/utils/convertTime.ts
  src/hooks/useTimer.ts
Labels: feat

#198 [Feat] Timer 이전으로 되돌리기
  src/common/Timer/utils/convertTime.ts
  src/hooks/useTimer.ts
Labels: feat

#217 [Feat] 게스트 유저 토큰 재발급 실패시 로컬스토리지 토큰 삭제
  src/apis/api.ts
Labels: feat

#220 [Fix]: 인게임 중 한 유저가 이탈할 시 방이 사라지는 버그 해결
  src/pages/GamePage/GamePage.tsx
  src/pages/GamePage/hooks/useWebsocket.ts
Labels: fix

#230 [Fix] 게임 목록 '전체' 탭에서 게임중인 방 목록 안보이게 수정
  src/pages/MainPage/GameRoomList.tsx
Labels: fix

#234 [Fix] 문장게임 오타 검출 로직 수정
  src/pages/GamePage/GameSentence/GameForm.tsx
Labels: fix

#228 [Fix] 타이머 버그 수정
  src/common/Ingame/IngameHeader.tsx
  src/pages/GamePage/common/RoundWaitModal.tsx
Labels: fix

#238 [Fix] UI 개선 - game autofocus
  src/pages/GamePage/GameCode/CodeForm.tsx
  src/pages/GamePage/GameSentence/GameForm.tsx
  src/pages/GamePage/GameWord/WordGameLayout.tsx
  src/pages/GamePage/hooks/useFocusInput.ts
Labels: fix

#246 [Fix] 인게임 이탈시 roomInfo 초기화
  src/pages/MainPage/MainPage.tsx
  src/store/useRoomInfoStore.ts
Labels: fix

#250 [Fix] 아무도 타이핑하지 않을시 2라운드 후 타이머 돌아가지 않는 버그 수정
  src/pages/GamePage/IngameWebsocketLayer.tsx
Labels: fix

#253 [Style] 라운드 종료 5초 전부터 타이머 깜빡임
  src/common/Ingame/IngameHeader.tsx
  tailwind.config.js
Labels: style

#272 [Style] 현재 접속자 본인 식별
  src/pages/MainPage/UserList.tsx
  src/pages/MainPage/UserListItem.tsx
Labels: style

#276 [Style] 게임 대기실 정보
  src/pages/GamePage/GameWaitingRoom/GameRoomInfo.tsx
Labels: style

#278 [Fix]: 브라우저 뒤로가기로 나간후 방 입장, 생성 이슈 해결
  src/pages/MainPage/MainPage.tsx
Labels: fix

#275 [Style] 유저 프로필 카드 스타일링
  src/pages/MainPage/UserCard.tsx
Labels: style

#282 [Style] 랭킹페이지 본인 표시
  src/pages/RankPage/RankItem.tsx
Labels: style

#284 [Style]: 게임 모드 설명 css 수정
  src/pages/GamePage/GameWaitingRoom/GameModeDescription.tsx
Labels: style

#285 [Feat] Toast 적용
  package.json
  src/App.tsx
  src/common/AuthRoute/AuthRoute.tsx
  src/pages/KaKaoLoginPage/KaKaoLoginPage.tsx
  src/pages/MainPage/CreateRoom/CreateRoomForm.tsx
  src/pages/NicknamePage/UpdateNickname/UpdateNicknameForm.tsx
  src/pages/StartPage/StartPage.tsx
  src/utils/storageFactory.ts
  src/utils/toast.ts
  yarn.lock
Labels: feat

#300 [Style] 방 목록 넘칠시 레이아웃 깨짐 수정 (긴...급...) 🚨
  src/pages/MainPage/GameRoomList.tsx
Labels: style

#307 리드미 기본 구조 업데이트
  README.md
Labels: documentation

#303 [Style] 랭킹 스크롤 넘칠시 레이아웃 깨짐 수정 (긴...급...) 🚨2
  src/pages/RankPage/RankList.tsx
Labels: style

#309 [📝docs]: Update Readme.md
  README.md
Labels: documentation
